<?
      $options=array(//опции
      "Экстерьер"=>array(
      182=>"Биксеноновые фары",
      218=>"Ксеноновые фары",
      235=>"Легкосплавные диски",
      148=>"Люк в крыше",
      184=>"Рейлинги на крыше",
      223=>"Тонированные стёкла",
      164=>"Фары противотуманные"),

      "Интерьер"=>array(
      196=>"Декоративные вставки",
      161=>"Обивка сидений - кожа",
      186=>"Обивка сидений - комбинированная",
      160=>"Обивка сидений - ткань",
      162=>"Спортивные передние сиденья"),

      "Управление"=>array(
      203=>"Гидроусилитель руля",
      165=>"Круиз-контроль",
      174=>"Парктроник",
      156=>"Руль кожаный",
      158=>"Руль спортивный",
      169=>"Сервотроник"),

      "Комфорт"=>array(
      151=>"Зеркала эл.регулируемые внешние с обогревом",
      168=>"Климат-контроль",
      225=>"Кондиционер",
      149=>"Обогрев передних сидений",
      152=>"Сиденья с эл.регулировкой по высоте",
      150=>"Стеклоподъемники эл."),

      "Мультимедиа"=>array(
      176=>"CD-проигрыватель",
      178=>"CD-чейнджер",
      177=>"mp3",
      154=>"Бортовой компьютер",
      185=>"Мультимедиа интерфейс",
      181=>"Навигационная система",
      183=>"Подготовка к установке мобильного телефона"),
      
      "Безопасность"=>array(
      155=>"ABS",
      175=>"ESP",
      147=>"Иммобилайзер",
      172=>"Крепление для детского сиденья",
      197=>"Передние подушки безопасности",
      205=>"Подушки безопасности боковые",
      206=>"Подушки безопасности для головы",
      180=>"Сигнализация ",
      195=>"Тормоза дисковые",
      146=>"Центральный замок"),
      
      "Дополнительно"=>array(
      219=>"Омыватели фар",
      171=>"Подвеска адаптивная пневматическая",
      167=>"Подвеска усиленная"));



$car_body=array(//тип кузова
        6=>"Внедорожник",
        1=>"Кабриолет",
        5=>"Купе",
        12=>"Лимузин",
        8=>"Микроавтобус",
        9=>"Минивэн",
        10=>"Пикап",
        3=>"Седан",
        4=>"Универсал",
        13=>"Универсал п.в.",
        11=>"Фургон",
        7=>"Фургон грузовой",
        2=>"Хэтчбек"
);

$car_gearbox = array(//коробка
        1=>"механическая",
        2=>"автоматическая"
);

$car_drivegear=array(//Привод
         1=>"Передний",
         2=>"Задний",
         3=>"Полноприводный"
);

$car_fuel=array(//тип двигателя
         1=>"Бензин",
         2=>"Дизель"
);

$sort_by=array(//сортировка
        7=>"year",
        6=>"name",
        5=>"town",
        4=>"diler",
        3=>"kontrakt",
        2=>"isset",
        1=>"price"
);
$models = array(
"Polo"=>array("",
    "Trendline",
    "Fly",
    "Comfortline",
    "Cross Polo"),
  
"Polo Sedan"=>array("",
    "Trendline",
    "Comfortline",
    "Highline"),

"Golf"=>array("",
    "Team",
    "Highline",
    "GTI",
    "R",
    "Comfortline"),

"Golf Plus"=>array("",
    "Trendline",
    "Comfortline"),

"Golf 7"=>array("",
    "Team",
    "Highline",
    "GTI",
    "R",
    "Comfortline"),

"Golf Variant"=>array("",
    "Trendline",
    "Comfortline"),
"Touran"=>array("",
    "Trendline",
    "Comfortlin",
    "Highline",
    "Cross",
    "Special"),
"Jetta"=>array("",
    "Pride",
    "Trendline",
    "Comfortline",
    "Highline"),
"Scirocco"=>"",
"Eos"=>"",
"Tiguan"=>array("",
    "Trend&amp;Fun",
    "Track&amp;Field",
    "Sport&amp;Style",
    "Track&amp;Style",
    "Fun",
    "Track",
    "Sport",
    "Style"),
"Passat"=>array("",
    "Trendline",
    "Comfortlin",
    "Highline",
    "Trend",
    "Comfort",
    "ComfortPlus",
    "Premium",
    "PremiumPlus"),
"Passat  Variant"=>array("",
    "Trendline",
    "Comfortlin",
    "Highline"),
"Passat  Alltrack"=>"",
"CC"=>"",
"Touareg"=>array("",
    "Life",
    "V6 TDI",
    "V6 FSI",
    "V8 TDI",
    "V8 FSI"),
"Caddy Kombi"=>array("",
    "Startline",
    "Trendline",
    "Comfortline",
    "Highline",
    "Maxi Startline",
    "Maxi Trendline (7 мест)",
    "Maxi Comfortline (7 мест)"),
"Caddy Kasten"=>array("",
    "Kasten (короткая база)",
    "Kombi (короткая база)",
    "Kasten (длинная база)",
    "Kombi (длинная база)"),
"Multivan"=>array("",
    "Long",
    "Comfortline",
    "Startline",
    "Business",
    "Highline",
    "Edition25"),
"Amarok"=>array("",
    "DoubleCab",
    "DoubleCab Trendline",
    "DoubleCab Highline"),
"Caravelle"=>array("",
    "Trendline",
    "Comfortline"),
"Crafter"=>array("",
     "30, колісна база 3250 мм",
     "30, колісна база 3665 мм",
     "50, колісна база 4325 мм",
     "30, колісна база 3665 мм",
     "30, колісна база 3665 мм",
     "35, колісна база 3665 мм,",
     "50, колісна база 4325 мм",
     "50, колісна база 3665 мм",
     "35, колісна база 3665 мм",
     "35, колісна база 4325 мм",
     "50, колісна база 4325 мм"),
"Crafter Pritschen"=>array("",
    "30, колісна база 3250 мм",
    "35, колісна база 3250 мм",
    "30, колісна база 3665 мм",
    "35, колісна база 3665 мм",
    "50, колісна база 3665 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм",
    "30, колісна база 3665 мм",
    "35, колісна база 3665 мм",
    "50, колісна база 3665 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм"),
"Crafter Kasten"=>array("",
    "30, колісна база 3250 мм",
    "35, колісна база 3250 мм",
    "30, колісна база 3665 мм",
    "35, колісна база 3665 мм",
    "50, колісна база 3665 мм",
    "30, колісна база 3665 мм",
    "35, колісна база 3665 мм",
    "50, колісна база 3665 мм",
    "35, колісна база 3665 мм",
    "50, колісна база 3665 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм",
    "35, колісна база 4325 мм",
    "50, колісна база 4325 мм"),
"Transporter Kasten"=>"",
"Transporter Kombi"=>"");
/*$models = array(
  "Polo"=>"",
  "Polo"=>"Trendline",
  "Polo"=>"Fly",
  "Polo"=>"Comfortline",
  "Polo"=>"Cross Polo",
  
  "Polo Sedan"=>"",
  "Polo Sedan"=>"Trendline",
  "Polo Sedan"=>"Comfortline",
  "Polo Sedan"=>"Highline",

  "Golf"=>"",
  "Golf"=>"Team",
  "Golf"=>"Highline",
  "Golf"=>"GTI",
  "Golf"=>"R",
  "Golf"=>"Comfortline",

  "Golf Plus"=>"",
  "Golf Plus"=>"Trendline",
  "Golf Plus"=>"Comfortline",

  "Golf Variant"=>"",
  "Golf Variant"=>"Trendline",
  "Golf Variant"=>"Comfortline",
"Touran"=>"",
"Touran"=>"Trendline",
"Touran"=>"Comfortlin",
"Touran"=>"Highline",
"Touran"=>"Cross",
"Touran"=>"Special",
"Jetta"=>"",
"Jetta"=>"Pride",
"Jetta"=>"Trendline",
"Jetta"=>"Comfortline",
"Jetta"=>"Highline",
"Scirocco"=>"",
"Eos"=>"",
"Tiguan"=>"",
"Tiguan"=>"Trend&amp;Fun",
"Tiguan"=>"Track&amp;Field",
"Tiguan"=>"Sport&amp;Style",
"Tiguan"=>"Track&amp;Style",
"Tiguan"=>"Fun",
"Tiguan"=>"Track",
"Tiguan"=>"Sport",
"Tiguan"=>"Style",
"Passat"=>"",
"Passat"=>"Trendline",
"Passat"=>"Comfortlin",
"Passat"=>"Highline",
"Passat"=>"Trend",
"Passat"=>"Comfort",
"Passat"=>"ComfortPlus",
"Passat"=>"Premium",
"Passat"=>"PremiumPlus",
"Passat  Variant"=>"",
"Passat  Variant"=>"Trendline",
"Passat  Variant"=>"Comfortlin",
"Passat  Variant"=>"Highline",
"Passat  Alltrack"=>"",
"CC"=>"",
"Touareg"=>"",
"Touareg"=>"Life",
"Touareg"=>"V6 TDI",
"Touareg"=>"V6 FSI",
"Touareg"=>"V8 TDI",
"Touareg"=>"V8 FSI",
"Caddy Kombi"=>"",
"Caddy Kombi"=>"Startline",
"Caddy Kombi"=>"Trendline",
"Caddy Kombi"=>"Comfortline",
"Caddy Kombi"=>"Highline",
"Caddy Kombi"=>"Maxi Startline",
"Caddy Kombi"=>"Maxi Trendline (7 мест)",
"Caddy Kombi"=>"Maxi Comfortline (7 мест)",
"Caddy Kasten"=>"",
"Caddy Kasten"=>"Kasten (короткая база)",
"Caddy Kasten"=>"Kombi (короткая база)",
"Caddy Kasten"=>"Kasten (длинная база)",
"Caddy Kasten"=>"Kombi (длинная база)",
"Multivan"=>"",
"Multivan"=>"Long",
"Multivan"=>"Comfortline",
"Multivan"=>"Startline",
"Multivan"=>"Business",
"Multivan"=>"Highline",
"Multivan"=>"Edition25",
"Amarok"=>"",
"Amarok"=>"DoubleCab",
"Amarok"=>"DoubleCab Trendline",
"Amarok"=>"DoubleCab Highline",
"Caravelle"=>"",
"Caravelle"=>"Trendline",
"Caravelle"=>"Comfortline",
"Crafter"=>"",
"Crafter"=>"30, колісна база 3250 мм",
"Crafter"=>"30, колісна база 3665 мм",
"Crafter"=>"50, колісна база 4325 мм",
"Crafter"=>"30, колісна база 3665 мм",
"Crafter"=>"30, колісна база 3665 мм",
"Crafter"=>"35, колісна база 3665 мм,",
"Crafter"=>"50, колісна база 4325 мм",
"Crafter"=>"50, колісна база 3665 мм",
"Crafter"=>"35, колісна база 3665 мм",
"Crafter"=>"35, колісна база 4325 мм",
"Crafter"=>"50, колісна база 4325 мм",
"Crafter  Pritschen"=>"",
"Crafter  Pritschen"=>"30, колісна база 3250 мм",
"Crafter  Pritschen"=>"35, колісна база 3250 мм",
"Crafter  Pritschen"=>"30, колісна база 3665 мм",
"Crafter  Pritschen"=>"35, колісна база 3665 мм",
"Crafter  Pritschen"=>"50, колісна база 3665 мм",
"Crafter  Pritschen"=>"35, колісна база 4325 мм",
"Crafter  Pritschen"=>"50, колісна база 4325 мм",
"Crafter  Pritschen"=>"30, колісна база 3665 мм",
"Crafter  Pritschen"=>"35, колісна база 3665 мм",
"Crafter  Pritschen"=>"50, колісна база 3665 мм",
"Crafter  Pritschen"=>"35, колісна база 4325 мм",
"Crafter  Pritschen"=>"50, колісна база 4325 мм",
"Crafter  Kasten"=>"",
"Crafter  Kasten"=>"30, колісна база 3250 мм",
"Crafter  Kasten"=>"35, колісна база 3250 мм",
"Crafter  Kasten"=>"30, колісна база 3665 мм",
"Crafter  Kasten"=>"35, колісна база 3665 мм",
"Crafter  Kasten"=>"50, колісна база 3665 мм",
"Crafter  Kasten"=>"30, колісна база 3665 мм",
"Crafter  Kasten"=>"35, колісна база 3665 мм",
"Crafter  Kasten"=>"50, колісна база 3665 мм",
"Crafter  Kasten"=>"35, колісна база 3665 мм",
"Crafter  Kasten"=>"50, колісна база 3665 мм",
"Crafter  Kasten"=>"35, колісна база 4325 мм",
"Crafter  Kasten"=>"50, колісна база 4325 мм",
"Crafter  Kasten"=>"35, колісна база 4325 мм",
"Crafter  Kasten"=>"50, колісна база 4325 мм",
"Crafter  Kasten"=>"35, колісна база 4325 мм",
"Crafter  Kasten"=>"50, колісна база 4325 мм",
"Crafter  Kasten"=>"35, колісна база 4325 мм",
"Crafter  Kasten"=>"50, колісна база 4325 мм",
"Transporter  Kasten"=>"",
"Transporter  Kombi"=>"");*/
?>